name: res2tim
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - torchvision==0.6.0
  - pytorch==1.5.0
  - pip:
    - dominate==2.5.2
    - opencv-python==4.4.0.42
    - pandas==1.1.1
    - tqdm==4.48.2
    - scipy==0.5.2
    - visdom==0.1.8
